"""
Tests for agent.variable_resolution — filling an anti-unification hole by
bounded, example-grounded selection (§2.5-2b).

An anti-unification product is incomplete: the lifted position is a `?vN` hole.
`resolve_variable` fills it by trying a *bounded, ordered* set of candidate
fillings and accepting the first that *reproduces every example output*. The
choice is therefore grounded in the example comparisons (P3/P4), never invented;
a task that supports no candidate yields None (so the rule is not falsely used).
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from agent.variable_resolution import resolve_variable


# ── a tiny grid/pair/task stand-in ─────────────────────────────────────
class _Grid:
    def __init__(self, raw):
        self.raw = raw


class _Pair:
    def __init__(self, inp, out):
        self.input_grid = _Grid(inp) if inp is not None else None
        self.output_grid = _Grid(out) if out is not None else None


class _Task:
    def __init__(self, pairs):
        self.example_pairs = pairs


def _task(*io):
    return _Task([_Pair(i, o) for i, o in io])


# A render that "applies" a candidate by adding the candidate's value to every
# cell; example outputs were generated by adding `2`, so only value==2 reproduces.
def _add_render(value):
    def render(rule, task, input_grid):
        return [[c + rule["k"] for c in row] for row in input_grid.raw]
    return render


def _instantiate(value):
    return {"k": value}


# ── tests ──────────────────────────────────────────────────────────────
def test_selects_the_reproducing_candidate():
    task = _task(([[1, 0]], [[3, 2]]), ([[5]], [[7]]))   # outputs = inputs + 2
    chosen = resolve_variable(task, [0, 1, 2, 3], _instantiate,
                              _add_render(None))
    assert chosen == 2


def test_returns_none_when_no_candidate_reproduces():
    task = _task(([[1]], [[100]]))                       # +2 never reaches 100
    chosen = resolve_variable(task, [0, 1, 2, 3], _instantiate,
                              _add_render(None))
    assert chosen is None


def test_priority_order_breaks_ties_deterministically():
    # When more than one candidate reproduces the examples, the first in order
    # wins — selection is deterministic, never ambiguous. Here the render ignores
    # the candidate entirely (every candidate reproduces the identity examples),
    # so only the *order* can decide.
    def identity_render(rule, task, input_grid):
        return [row[:] for row in input_grid.raw]
    task = _task(([[4]], [[4]]))
    chosen = resolve_variable(task, ["b", "a"], _instantiate, identity_render)
    assert chosen == "b"      # first candidate, not min/sorted


def test_no_examples_yields_none():
    assert resolve_variable(_Task([]), [0, 1], _instantiate,
                            _add_render(None)) is None


def test_skips_pairs_missing_a_side():
    # A pair lacking input or output is ignored; selection rests on the complete
    # pairs only (here the one complete pair fixes the answer at +2).
    task = _Task([_Pair([[1]], None), _Pair([[1]], [[3]])])
    chosen = resolve_variable(task, [1, 2], _instantiate, _add_render(None))
    assert chosen == 2
